### ISSUE TITLE
How to handle 'null' entries in modinfo.json

### ISSUE THREAD

**Issue by ghost** [anno-mods/Modinfo#7]
Many entries in [modinfo.json](https://github.com/taubenangriff/Modinfo/blob/master/modinfo.json) are **null**. 

Isn't it better to simply leave them out in the actual mod, since they will not be noticed during parsing anyway?

For sure it's good to use **null** in this example file just for overview and possibility to easy copy and adjust it.

**Comment by taubenangriff** [comment]
The many null values are just what C# serializing spits out. Moreover doesn't not providing them screw with the serialization process?

**Comment by ghost** [comment]
Good point. Don't know. Maybe @EtienneDx and @LemonDrop1228 can help here with C#. Guess it depends how and which library you use. ❓

**Comment by taubenangriff** [comment]
Visual C# comes with built in support for json serialization. I used default serialization settings and it printed the null values instead of leaving out iirc.

**Comment by EtienneDx** [comment]
I haven't work on serialization in a while, but since everything in CSharp is instance-based, I don't see any problem in having null-valued fields. I think the only difference there would be the file readability for human eyes, but the computer wouldn't care.

I'll start working on reading the json files for AMM soon, I'll tell you then if it's a problem

**Comment by jakobharder** [comment]
Omit them. All currently used tools can deal with it afaik.
